dist: trusty
sudo: false
language: php

php:
  - 7.1
  - 7.2

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update --no-interaction --prefer-dist $COMPOSER_ARGS

script:
  - php vendor/bin/phpcs
  - php vendor/bin/phpunit --coverage-clover=build/logs/clover.xml

after_success:
  - travis_retry composer require php-coveralls/php-coveralls
  - travis_retry php vendor/bin/php-coveralls --coverage_clover=build/logs/clover.xml -v
